In [1]:
import numpy as np

# Fundamentos y Creación de Arrays

In [ ]:
# Crea uin array de 1D de 10 ceros

arr = np.zeros(10, dtype=int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
# Crea un array 1D de 8 elementos con el valor 5
arr = np.full(8, 5)
print(arr)

[5 5 5 5 5 5 5 5]


In [ ]:
# Crea un array 1D con números del 10 al 49 inclusive
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Crea una matriz 3x3 de números enteros del 0 al 8
arr = np.reshape(np.arange(9), (3, 3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
# Crea una matriz identidad 4x4
arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
# Invierte el orden de un array 1D
arr = np.arange(11)
print(arr)
rev = np.flip(arr)
print(rev)

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]


In [ ]:
# Crea un array de 10 valores aleatorios uniformes
arr = np.random.uniform(0, 10, size=10)
print(arr)

[5.85697564 1.94352142 1.39203946 1.12750064 5.53010447 6.00625799
 9.20381919 9.68846274 2.8999311  6.65728757]


In [ ]:
# Encuentra el número de bytes y el tipo de datos de un array dado
arr = np.array([1, 2, 3, 45, 6, 7, 8, 9])
print(arr.nbytes)
print(arr.dtype)

64
int64


In [5]:
# Convierte una lista de Python [1,2,3,4,5] rn un srray de Numpy
lis = [1, 2, 3, 4, 5]
print(type(lis))

arr = np.array(lis)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
# ¿Cuál es el resultado de la siguiente expresión 0 * np.nan?
print(0 * np.nan)
print(type(np.nan))
print(np.dtype(type(np.nan)))

nan
<class 'float'>
float64


In [10]:
# Crea un array 1D de números pares del 2 al 20
arr = np.arange(2, 21, 2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
# Extrae todos los elementos impares de un array dado
# opción 1
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
impar = arr[arr % 2 != 0]
print(impar)

# opción 2
index = np.where(arr % 2 != 0)
impar = arr[index]
print(impar)

[ 1  3  5  7  9 11 13 15 17 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [20]:
# Reemplaza todos los valores mayores que 10 en un array con el valor de 10
# opción 1
arr = np.array([5, 12, 8, 15, 3, 20, 9, 10, 7, 18])
res = np.where(arr > 10, 10, arr)
print(res)

# opción 2
res = arr.copy()
res[res > 10] = 10
print(res)

[ 5 10  8 10  3 10  9 10  7 10]
[ 5 10  8 10  3 10  9 10  7 10]


In [38]:
# Normaliza una matriz aleatoria 5x5
arr = np.random.uniform(20, 100, size=(5, 5))
print(arr)
print()
res = (arr - arr.min()) / (arr.max() - arr.min())
print(res)

[[21.20699127 93.10009498 94.07524301 66.62963017 45.00956398]
 [99.86140544 32.00112407 99.55851778 29.99711921 48.08437131]
 [62.48466597 45.88829108 84.51338942 96.82554077 63.15795448]
 [59.9460222  84.08991257 83.76791616 29.58930296 39.67886853]
 [70.14264706 50.18002057 25.07659407 49.85589045 25.92926818]]

[[0.         0.91403775 0.92643563 0.57749637 0.30262221]
 [1.         0.13723493 0.99614913 0.11175632 0.34171483]
 [0.52479794 0.31379421 0.80486771 0.96140249 0.53335803]
 [0.49252202 0.79948369 0.79538988 0.10657141 0.23484858]
 [0.62216032 0.36835859 0.04919753 0.36423765 0.06003829]]


In [ ]:
# Crea un array 2D y calcula la suma de todos sus elementos
arr = np.random.randint(0, 100, size=(3, 3))
print(arr)
print()
res = np.sum(arr)
print(res)

[[82 74 71]
 [49 62 17]
 [ 3 87 65]]

510


In [41]:
# ¿Cómo se obtiene el número de dimensiones (ndim) de un array?
arr = np.random.randint(0, 100, size=(3, 3))
print(arr.ndim)

2


In [ ]:
# Extrae la primera fila de una matriz 3x4
arr = np.random.randint(0, 50, size=(3, 4))
print(arr)
print()
print(arr[0])

[[19 28  5  2]
 [44 28 14 28]
 [45 41 16 23]]

[19 28  5  2]


In [ ]:
# Crea una matriz 5x5 con un borde de unos y el interior de ceros
arr = np.zeros((5, 5), dtype=int)
print(arr)
print()
arr[[0, -1], :] = 1
arr[:, [0, -1]] = 1
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
# Crea una array de 5 valores espaciados uniformemente entre 0 y 1
arr = np.random.uniform(0, 1, size=(5))
print(arr)

[0.66433387 0.69749104 0.65605456 0.23473077 0.1559331 ]


In [56]:
# Suma dos array 1D elemento por elemento
arr1 = np.random.randint(0, 30, size=10)
print(arr1)
arr2 = np.random.randint(0, 30, size=10)
print(arr2)
res = arr1 + arr2
print(res)

[22  2  3 25 20 26  4  1  9 18]
[17  3 21 10  9 11 10 17 27 25]
[39  5 24 35 29 37 14 18 36 43]


In [ ]:
# Crea un array booleano 3x3 domne True indica si el elemento es mayor que 0.5 en un array de aleatorios
arr = np.random.rand(3, 3)
print(arr)
print()
res = arr > 0.5
print(res)

[[0.00753016 0.28930038 0.40236056]
 [0.6289274  0.4505026  0.45365097]
 [0.02009958 0.96251252 0.68638135]]

[[False False False]
 [ True False False]
 [False  True  True]]


In [3]:
# Convierte un array de float a int
arr_float = np.array([1.7, 2.3, 3.8, 4.1, 5.9])

# Método 1: truncamiento
arr = arr_float.astype(int)
print(arr)

# Método 2: redondeo
ar_round = np.round(arr_float).astype(int)
print(ar_round)

[1 2 3 4 5]
[2 2 4 4 6]
