# Intermedio -> Manipulación, Indexación y Operaciones

In [13]:
import numpy as np

In [ ]:
# Crea una matriz 2D y haz una transposición
arr = np.random.randint(40, 100, size=(2, 2))
print(arr)
print()
print(arr.transpose())

[[40 42]
 [87 43]]

[[40 87]
 [42 43]]


In [ ]:
# Considera un array A de forma (5,5,3). Calcula la suma a lo largo del ultimo eje
arr = np.random.rand(5, 5, 3)
print(f"Array de forma {arr.shape}")
suma = np.sum(arr, axis=2)
print(f"Suma a lo largo del ultimo eje {suma.shape}")
print(suma)

Array de forma (5, 5, 3)
Suma a lo largo del ultimo eje (5, 5)
[[1.6615924  1.29367587 1.16056795 2.57360734 1.3119892 ]
 [1.13315948 1.85216602 1.4871219  1.03527096 1.4440667 ]
 [1.83568028 1.58647319 1.92316749 0.75353392 1.82510385]
 [0.90136424 0.43913204 1.58667382 1.23839253 1.11716098]
 [0.67206326 1.40348175 1.05904249 1.41941426 1.14887093]]


In [ ]:
# Intercambia la primera y la última fila de una matriz 5x5 dada
random_matrix = np.random.randint(1, 100, size=(5, 5))
print(random_matrix, "\n")
random_matrix[[0, -1]] = random_matrix[[-1, 0]]
print(random_matrix)

[[47 33 72 94 68]
 [ 2  2 83 27 91]
 [52 21 84 41 51]
 [94 53 30 48 29]
 [94 66 90 18 88]] 

[[94 66 90 18 88]
 [ 2  2 83 27 91]
 [52 21 84 41 51]
 [94 53 30 48 29]
 [47 33 72 94 68]]


In [ ]:
# Crea un array de números aleatorios y encuentra los 5 valores más grandes
arr = np.random.randint(0, 100, size=(15))
print(arr)
k = 5
max_value = np.partition(arr, -k)[-k:]
print(max_value)

[14 92 33 75 78 14 38  6 85 31 17 53 74 60 95]
[75 78 85 92 95]


In [ ]:
# Con una matriz 2D, cálcula la media a lo largo de las columnas
arr = np.random.randint(0, 100, size=(5, 5))
print(arr)
res = np.mean(arr, axis=0)
print(res)

[[99 86 30 38 72]
 [63  6 65 49 90]
 [64 68 92 22 71]
 [42 14 89 42 51]
 [73  9 78 57 94]]
[68.2 36.6 70.8 41.6 75.6]


In [ ]:
# Dada una matriz 2D, selecciona solo las filas donde el valor de la primera columna sea mayor que 5
arr = np.random.randint(0, 10, size=(5, 7))
print(arr)
res = arr[arr[:, 0] > 5]
print("\n", res)

[[1 6 1 8 9 1 6]
 [9 5 3 5 7 9 5]
 [8 2 1 4 8 9 0]
 [9 5 0 1 3 7 7]
 [6 2 6 0 0 7 4]]

 [[9 5 3 5 7 9 5]
 [8 2 1 4 8 9 0]
 [9 5 0 1 3 7 7]
 [6 2 6 0 0 7 4]]


In [ ]:
# ¿Cómo se puede hacer broadcasting para sumar un array 1D a cada fila de un array 2D?
arr1 = np.random.randint(10, 60, size=(5))
print(arr1)
arr2 = np.random.randint(10, 60, size=(2, 5))
print(arr2)
res = arr1 + arr2
print(res)

[18 50 19 10 53]
[[13 12 47 26 46]
 [16 34 20 42 18]]
[[31 62 66 36 99]
 [34 84 39 52 71]]


In [ ]:
# Crea un array 1D y dividelo (split) en 3 sub-arrays
arr = np.random.randint(0, 10, size=(12))
print(arr)
print(arr[:4])
print(arr[4:8])
print(arr[8:])

[4 2 7 4 5 8 5 9 1 5 1 4]
[4 2 7 4]
[5 8 5 9]
[1 5 1 4]


In [ ]:
# Considera dos arrays A y B. Determina qué elementos de A también está presentes en B
A = np.array([1, 2, 3, 4, 5, 6])
B = np.array([4, 5, 6, 7, 8, 9])
inter = np.intersect1d(A, B)
print(inter)

[4 5 6]


In [18]:
# Cálcula la desviación estándar de una matriz 3x3 de números aleatorios
arr = np.random.rand(10)
print(arr)
res = np.std(arr)
print(res)

[0.45055595 0.98561803 0.47022652 0.09725553 0.40575418 0.97168809
 0.97648056 0.40913567 0.36795862 0.07773236]
0.3254618867518809


In [ ]:
# ¿Cómo se elimina las filas que contienen valores NaN de una matriz 2D?
matrix = np.array(
    [[1, 2, 3], [4, np.nan, 6], [7, 8, 9], [np.nan, np.nan, np.nan], [10, 11, 12]]
)
print(matrix)
res = matrix[~np.any(np.isnan(matrix), axis=1)]
print(res)

[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]
 [nan nan nan]
 [10. 11. 12.]]
[[ 1.  2.  3.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [29]:
# Crea una matriz NxN, crea un patrón de tablero de ajedrez (alternando 0 y 1)
table = np.zeros((8, 8), dtype=int)
table[1::2, ::2] = 1  # filas impares
table[::2, 1::2] = 1
print(table, "\n")

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]] 



In [ ]:
# Ordena las filas de una matriz 2D basándote en los valores de la segunda columna
matrix = np.array([[5, 2, 8], [1, 9, 4], [3, 1, 7], [7, 5, 2], [2, 3, 6]])
print(matrix)
print()

indices = np.argsort(matrix[:, 1])
print(indices)
print()

matriz_res = matrix[indices]
print(matriz_res)

[[5 2 8]
 [1 9 4]
 [3 1 7]
 [7 5 2]
 [2 3 6]]

[2 0 4 3 1]

[[3 1 7]
 [5 2 8]
 [2 3 6]
 [7 5 2]
 [1 9 4]]


In [ ]:
# ¿Cómo se puede convertir un array 1D de forma N a una matriz 2D de forma (1, N) (agregar una dimensión con newaxis)
arr = np.random.randint(5, 75, size=(7))
print(arr)
print(arr.shape)

arr2 = arr[np.newaxis, :]
print(arr2)
print(arr2.shape)

[67 66 35 54 47  6 43]
(7,)
[[67 66 35 54 47  6 43]]
(1, 7)


In [42]:
# Cálcula el cuartil superior (75 percentil) de un array de 100 números aleatorios
data = np.array([12, 15, 16, 18, 20, 12, 18])
data.sort()
q3 = np.quantile(data, 0.75)
print(q3)

18.0


In [ ]:
# Encuentra la intersección (elementos comunes) de dos arrays 1D
arr1 = np.random.randint(1, 10, size=(7))
print(arr1)
arr2 = np.random.randint(1, 10, size=(7))
print(arr2)
res = np.intersect1d(arr1, arr2)
print(res)

[6 1 5 5 1 6 6]
[6 8 2 7 6 4 9]
[6]
